name: Deploy Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish Site
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: latest
          run_install: true

      - name: Build
        run: pnpm build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 73764c8fd1a6e160307f47096ede19b7
          projectName: corridorrequests
          directory: .svelte-kit/cloudflare
